# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'SVC-IAC-datafactory'
    subscriptionId: '4f2408c2-9029-4bdf-9195-a8e961e5c591'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-rg01'
    location: 'Australia Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/KanduriR/Datafactory-databricks-arm-template/blob/master/arm-datafactory-databricks-template/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/KanduriR/Datafactory-databricks-arm-template/blob/master/arm-datafactory-databricks-template/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'ARMDeployPipelineTemplate'
